vich_uploader:
    db_driver: orm

    mappings:
        recipe_images:
            uri_prefix: /images/recipes
            upload_destination: '%kernel.project_dir%/public/images/recipes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
